### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by ubuntupunk** [Toasterbirb/rofi-tube#1]
the invidious site appears to be down, there are other options here https://api.invidious.io
I tried updating with the new sites, but search fails to return data.

**Comment by Toasterbirb** [comment]
Hey! Sorry for the late reply
Yes, it seems that the main invidious instance is down. I'll add a variable to the script to make it simpler to change the instance to account for these cases. I'll also change the default instance to yewtu.be for now. I have personally been using that recently

**Comment by Toasterbirb** [comment]
I ended up staying with invidious.snopyta.org and switched from scraping to using the invidious API. Should be way more stable and future proof. There's a dependency to `jq` now though, but that shouldn't be a huge problem.
